### ISSUE TITLE
Failed to handle openURL

### ISSUE THREAD

**Issue by comtaler** [firebase/quickstart-unity#19]
I am using Firebase for my game and we also integrated Facebook. However, after I connect to facebook on iOS, it stays on the webview and does not return back to the game. I got a hint from (http://stackoverflow.com/questions/35100809/unity-facebook-sdk-ios-9-2-not-returning-to-app) and finally figured that it is Firebase plugin that failed to handle openURL. After removing Firebase from the project, facebook login works fine.

**Comment by stewartmiles** [comment]
Which Firebase component did you remove which resulted in this working?
Any chance it was FirebaseMessaging?  If so I think we have a fix in the
pipeline for this.

**Comment by comtaler** [comment]
I removed all Firebase plugins (messaging, analytics, and dynamic links)

**Comment by stewartmiles** [comment]
If you just add Analytics do things start working?

**Comment by stewartmiles** [comment]
I think this issue is associated with the way we were swizzling methods on the app delegate in Messaging and Invites plugins.  We have a fix which will be released soon.

**Comment by stewartmiles** [comment]
I'm pleased to announce that we released:

- Firebase C++ SDK 2.1.0 (release notes [here](https://firebase.google.com/support/release-notes/cpp-relnotes#2.1.0), download [here](https://firebase.google.com/docs/cpp/setup))
- Firebase Unity SDK 1.1.0 (release notes [here](https://firebase.google.com/support/release-notes/unity#1.1.0), download [here](https://firebase.google.com/docs/unity/setup))

I believe this should resolve your issue.  If not, please let us know and we'll take a look.

Cheers,
Stewart

**Comment by comtaler** [comment]
After updating to the latest SDK, the problem is still there.

**Comment by stewartmiles** [comment]
Are you able to reproduce this issue with one of our samples?  For example, if you add the Facebook plugin to the Analytics sample does it fail in the same way?

**Comment by comtaler** [comment]
Here is what we found. The plugin works fine with the sample project but failed with out project. The difference is that in our project, after importing the sdk, it throws StackOverflowException as another bug I reported here ([https://github.com/firebase/quickstart-unity/issues/27](url)). I think that prevents Unity from patching Info.plist file because I don't find anything being added to "URL Types" there. Once the other issue is fixed, I can verify whether this one is fixed as well.

**Comment by PimDeWitte** [comment]
I think I'm experiencing the same issue. Found an interesting post on Facebook's bug reports that might be related. 

https://developers.facebook.com/bugs/1259676200763720/

Also, I confirmed on 1.0 that the values from both Facebook and Firebase are added to the URL types just fine:
<img width="409" alt="screen shot 2016-12-16 at 11 59 36 pm" src="https://cloud.githubusercontent.com/assets/8763534/21285386/bf811ad0-c3eb-11e6-9480-1650d24412a0.png">

Here's a video that shows the error with Facebook.
Does Firebase's libraries edit the openUrl at all? 

@comtaler how did you guys go about fixing this?

**Comment by PimDeWitte** [comment]
Edit:

Fixed it by removing Firebase Invites.

**Comment by PimDeWitte** [comment]
Also @comtaler if you're using 5.5 don't forget to implement this:
Just drag it in Plugins/iOS
https://bitbucket.org/snippets/etliaojing/aanKj

Source:
https://developers.facebook.com/bugs/900542723380664/

**Comment by comtaler** [comment]
@PimDeWitte We found the Unity 5.5 bug earlier and have patched it. But I think the patch is not related to this bug.

**Comment by PimDeWitte** [comment]
Agreed. Removing firebase invites fixed it for me, All the other libs are fine.

**Comment by PimDeWitte** [comment]
PS: This was with 1.0, I haven't tried it with 1.1 - so you may want to try that?

**Comment by comtaler** [comment]
@PimDeWitte I am already using 1.1

**Comment by comtaler** [comment]
@stewartmiles I got rid of the error reported in #27. But this problem still exists.

**Comment by stewartmiles** [comment]
Feels like the same issue as https://github.com/firebase/quickstart-unity/issues/33 which we believe we have a fix for.  Will update the bug when we've cut a release.

**Comment by stewartmiles** [comment]
This should be resolved in version 1.1.1
https://firebase.google.com/support/release-notes/unity#1.1.1
