### ISSUE TITLE
Crash in firebase::messaging::ProcessMessages

### ISSUE THREAD

**Issue by youdk** [firebase/quickstart-unity#294]
We upgrade Firebase to 5.3.1 after we upgraded Unity from 2018.1.4 to 2018.2.15. We got a lot of Firebase related crashes, both on iOS and Android.

01-09 11:59:47.516 1616-2342/? W/Unity: Error loading serialized FCM messages. Messages may have been dropped! (This is due to a change in internal serialization format. You should only see this once.
     
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
01-09 11:59:47.516 1616-2342/? E/Unity: Invalid event type! This event cannot be processed.
     
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
01-09 11:59:47.516 1616-1681/? I/Unity: Received Registration Token: dwohdZJwPjk:APA91bGeQqlm9-CLITK3cnV38V8uODzeFnDPe4EJVcIbOdiz6GpBnvRy5XIQRNIJ11SXsMklY_K8p51_iUSo3SibXF1fmC0v9KKm4Vo25rVZBRPe5T-4Tp3QAN5F5_C3Xx1c44UxuNyv
01-09 11:59:47.516 1616-2342/? W/Unity: Error loading serialized FCM messages. Messages may have been dropped! (This is due to a change in internal serialization format. You should only see this once.
     
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
01-09 11:59:47.526 1616-2342/? E/Unity: Invalid event type! This event cannot be processed.
     
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
01-09 11:59:47.526 1616-2342/? W/Unity: Error loading serialized FCM messages. Messages may have been dropped! (This is due to a change in internal serialization format. You should only see this once.
     
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
01-09 11:59:47.526 1616-2342/? E/CRASH: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 107ffd6f
    *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'google/hammerhead/hammerhead:4.4.4/KTU84P/1227136:user/release-keys'
    Revision: '11'
    pid: 1616, tid: 2342, name: UnityMain  
        r0 86f94be4  r1 107ffd6f  r2 00000000  r3 88454a9c
        r4 86f94be4  r5 00000004  r6 86f94b4c  r7 86f94b28
        r8 862c7f43  r9 000000b4  sl 88454b38  fp 88454b19
        ip 09264001  sp 88454aa8  lr 8622909d  pc 8622a0ca  cpsr 884547b8
    backtrace:
01-09 11:59:47.766 1616-1681/? A/MessageQueue: IdleHandler threw exception
    java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 107ffd6f
    Build fingerprint: 'google/hammerhead/hammerhead:4.4.4/KTU84P/1227136:user/release-keys'
    Revision: '11'
    pid: 1616, tid: 2342, name: UnityMain  
        r0 86f94be4  r1 107ffd6f  r2 00000000  r3 88454a9c
        r4 86f94be4  r5 00000004  r6 86f94b4c  r7 86f94b28
        r8 862c7f43  r9 000000b4  sl 88454b38  fp 88454b19
        ip 09264001  sp 88454aa8  lr 8622909d  pc 8622a0ca  cpsr 884547b8
    
        at libFirebaseCppApp-5.000d90ca(Native Method)
        at libFirebaseCppApp-5.firebase::messaging::ProcessMessages()(messaging:1656)
        at libFirebaseCppApp-5.000d8829(Native Method)
        at libc.__thread_entry(__thread_entry:72)
        at libc.pthread_create(pthread_create:240)

Can someone help?

I also found a thread discussing this issue:
https://groups.google.com/forum/?hl=zh-Tw#!topic/firebase-talk/4rkl0vtfgCY
Native Crash - Firebase 5.2.1 FCM Messaging with Unity

**Comment by chkuang-g** [comment]
@youdk Thank you for reporting this issue. 

I would need some more information.

- Which Firebase version did you upgrade from?
- Are you able to repro these crashes with our [Unity Messaging testapp](https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp)?
- Does the crash still happen if you upgrade to [Firebase 5.4.1](https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_5.4.1.zip)? (Not suggesting the latest 5.4.3 due to a [crash issue on iOS when app is closed](https://github.com/firebase/quickstart-unity/issues/271).  The fix will be included in an upcoming release.) 
- Does the crash still happens if you remove the plugins (all Firebase related folders under Assets/Firebase/ and Assets/Plugins/ folders) and reinstall the plugin again?
- You mentioned the crash happens to iOS, could you provide more context about those crashes or other crashes on Android?

Thank you!
Shawn

**Comment by youdk** [comment]
Hi, Firebase

	Thanks for your reply.
	
>Which Firebase version did you upgrade from?
We upgrade firebase sdk from 4.4.3 to 5.3.1.
The background is, after we upgraded untiy from 2018.1.4f to 2018.2.15f, we got a lot of crash, then we thought maybe those plugins needed to be upgraded as well, then we decided to upgrade Firebase sdk, we chose firebase 5.4.3 as the first choice, but we got some runtime error, so we downgrade a little bit to 5.3.1.
The runtime error of 5.4.3 is:
Unable to find FirebaseCppApp-5.4.3
12-26 18:41:12.586 25547-25599/? E/Unity: DllNotFoundException: Unable to load DLL 'FirebaseCppApp-5.4.3': The specified module could not be found.
      at Firebase.AppUtilPINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_AppUtil (Firebase.ExceptionDelegate applicationDelegate, Firebase.ExceptionDelegate arithmeticDelegate, Firebase.ExceptionDelegate divideByZeroDelegate, Firebase.ExceptionDelegate indexOutOfRangeDelegate, Firebase.ExceptionDelegate invalidCastDelegate, Firebase.ExceptionDelegate invalidOperationDelegate, Firebase.ExceptionDelegate ioDelegate, Firebase.ExceptionDelegate nullReferenceDelegate, Firebase.ExceptionDelegate outOfMemoryDelegate, Firebase.ExceptionDelegate overflowDelegate, Firebase.ExceptionDelegate systemExceptionDelegate) [0x00000] in <filename unknown>:0 
      at Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () [0x00000] in <filename unknown>:0 
      at Firebase.AppUtilPINVOKE..cctor () [0x00000] in <filename unknown>:0 
      at Firebase.AppUtil.SetLogFunction (Firebase.LogMessageDelegate arg0) [0x00000] in <filename
      

>Are you able to repro these crashes with our Unity Messaging testapp?
I didn't try on the testapp, but I don't think I can reproduce it. We got those crash from Fabric. Also our team member met this crash twice. It's not 100% reproducable.

>Does the crash still happen if you upgrade to Firebase 5.4.1? (Not suggesting the latest 5.4.3 due to a crash issue on iOS when app is closed. The fix will be included in an upcoming release.)
We didn't try on Firebase 5.4.1 yet. Are you suggesting we try on 5.4.1? 

>Does the crash still happens if you remove the plugins (all Firebase related folders under Assets/Firebase/ and Assets/Plugins/ folders) and reinstall the plugin again?
Yes, we removed the whole plugin folder and reimport firebase sdk again. I know firebase sdk version inconformity would cause some crashes.

>You mentioned the crash happens to iOS, could you provide more context about those crashes or other crashes on Android?
OK, I can't find the iOS crash log now, these are Android crash logs:

**************************************
CRASH LOG 1:
**************************************

01-09 11:59:47.506 1616-1681/? I/Unity: Firebase App initializing app com.test.app (default 1).
01-09 11:59:47.506 1616-1681/? I/Unity: Firebase Analytics API Initializing
01-09 11:59:47.506 1616-1681/? I/Unity: analytics API Initialized
01-09 11:59:47.506 1616-1681/? I/Unity: Firebase Cloud Messaging API Initialized
01-09 11:59:47.516 1616-1681/? I/Unity: Firebase Messaging Initialized
01-09 11:59:47.516 1616-2342/? W/Unity: Error loading serialized FCM messages. Messages may have been dropped! (This is due to a change in internal serialization format. You should only see this once.
     
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
01-09 11:59:47.516 1616-2342/? E/Unity: Invalid event type! This event cannot be processed.
     
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
01-09 11:59:47.516 1616-1681/? I/Unity: Received Registration Token: dwohdZJwPjk:APA91bGeQqlm9-CLITK3cnV38V8uODzeFnDPe4EJVcIbOdiz6GpBnvRy5XIQRNIJ11SXsMklY_K8p51_iUSo3SibXF1fmC0v9KKm4Vo25rVZBRPe5T-4Tp3QAN5F5_C3Xx1c44UxuNyv
01-09 11:59:47.516 1616-2342/? W/Unity: Error loading serialized FCM messages. Messages may have been dropped! (This is due to a change in internal serialization format. You should only see this once.
     
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
01-09 11:59:47.526 1616-2342/? E/Unity: Invalid event type! This event cannot be processed.
     
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
01-09 11:59:47.526 1616-2342/? W/Unity: Error loading serialized FCM messages. Messages may have been dropped! (This is due to a change in internal serialization format. You should only see this once.
     
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
01-09 11:59:47.526 1616-2342/? E/CRASH: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 107ffd6f
    *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'google/hammerhead/hammerhead:4.4.4/KTU84P/1227136:user/release-keys'
    Revision: '11'
    pid: 1616, tid: 2342, name: UnityMain  
        r0 86f94be4  r1 107ffd6f  r2 00000000  r3 88454a9c
        r4 86f94be4  r5 00000004  r6 86f94b4c  r7 86f94b28
        r8 862c7f43  r9 000000b4  sl 88454b38  fp 88454b19
        ip 09264001  sp 88454aa8  lr 8622909d  pc 8622a0ca  cpsr 884547b8
    backtrace:
01-09 11:59:47.766 1616-1681/? A/MessageQueue: IdleHandler threw exception
    java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 107ffd6f
    Build fingerprint: 'google/hammerhead/hammerhead:4.4.4/KTU84P/1227136:user/release-keys'
    Revision: '11'
    pid: 1616, tid: 2342, name: UnityMain  
        r0 86f94be4  r1 107ffd6f  r2 00000000  r3 88454a9c
        r4 86f94be4  r5 00000004  r6 86f94b4c  r7 86f94b28
        r8 862c7f43  r9 000000b4  sl 88454b38  fp 88454b19
        ip 09264001  sp 88454aa8  lr 8622909d  pc 8622a0ca  cpsr 884547b8
    
        at libFirebaseCppApp-5.000d90ca(Native Method)
        at libFirebaseCppApp-5.firebase::messaging::ProcessMessages()(messaging:1656)
        at libFirebaseCppApp-5.000d8829(Native Method)
        at libc.__thread_entry(__thread_entry:72)
        at libc.pthread_create(pthread_create:240)
        
        
        
**************************************
CRASH LOG 2:
**************************************
2019-01-16 16:15:31.327 3006-3291/? E/CRASH: Build fingerprint: 'google/angler/angler:8.1.0/OPM7.181005.003/4984324:user/release-keys'
2019-01-16 16:15:31.579 3006-3064/? E/MessageQueue: IdleHandler threw exception
    java.lang.Error: signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr bb77f6b9
    Build fingerprint: 'google/angler/angler:8.1.0/OPM7.181005.003/4984324:user/release-keys'
    Revision: '0'
    pid: 3006, tid: 3291, name: Thread-48 
        r0 bb77f6bd  r1 00000008  r2 00000004  r3 00000000
        r4 00000000  r5 ba8bf860  r6 bb77f6b9  r7 bb77f6b9
        r8 bead2f43  r9 0000003d  sl bb77f6d8  fp bb77f6b9
        ip beaf0e68  sp bb77f648  lr bea23e0f  pc bea3406c  cpsr bb77f358
    
        at libFirebaseCppApp-5.firebase::messaging::ProcessMessages()(messaging:1611)
        at libFirebaseCppApp-5.000d8829(Native Method)
        at libc.__pthread_start(void*)(__pthread_start:22)
        at libc.__start_thread(__start_thread:32)

**Comment by chkuang-g** [comment]
@appadvisorydev Your crash is related to [this thread](https://github.com/firebase/quickstart-unity/issues/271). This should only happen to 5.4.2 or later.  We will release fix in the next release.  At the meantime, you can remove the Firebase Plugin and install [Firebase 5.4.1](https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_5.4.1.zip). 

@youdk Could you try [Firebase 5.4.1](https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_5.4.1.zip) on your side?  Let me see if I can repro the DllNotFound exception and the message crash on our end.

**Comment by youdk** [comment]
@chkuang-g  Thanks for your advice, we will try Firebase 5.4.1 in next release and see what will happen.

**Comment by youdk** [comment]
@chkuang-g We tried to integrate Firebase 5.4.1 to our project, but it crashed when launching our game.
(We have removed the whole firebase related folder and re-imported from fresh) We have tried to upgrade firebase sdk and build on several different computer, they all crashed and crash log are the same:

01-18 20:07:30.389 4264-4264/com.testapp.demo E/Zygote: v2
01-18 20:07:30.389 4264-4264/com.testapp.demo I/libpersona: KNOX_SDCARD checking this for 10896
    KNOX_SDCARD not a persona
01-18 20:07:30.392 4264-4264/com.testapp.demo E/Zygote: accessInfo : 0
01-18 20:07:30.393 4264-4264/com.testapp.demo W/SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SECMOBILE_7.0_0010, [-1 -1 -1 -1 0 1]
01-18 20:07:30.396 4264-4264/com.testapp.demo I/SELinux: SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.testapp.demo 
01-18 20:07:30.402 4264-4264/com.testapp.demo I/art: Late-enabling -Xcheck:jni
01-18 20:07:30.435 4264-4264/com.testapp.demo D/TimaKeyStoreProvider: TimaKeyStore is not enabled: cannot add TimaSignature Service and generateKeyPair Service
01-18 20:07:30.557 4264-4264/com.testapp.demo I/MultiDex: VM with version 2.1.0 has multidex support
    install
    VM has multidex support, MultiDex support library is disabled.
01-18 20:07:30.572 4264-4264/com.testapp.demo W/art: Class com.google.android.gms.internal.measurement.zzea failed lock verification and will run slower.
    Common causes for lock verification issues are non-optimized dex code
    and incorrect proguard optimizations.
01-18 20:07:30.576 4264-4264/com.testapp.demo W/art: Class com.google.firebase.analytics.FirebaseAnalytics failed lock verification and will run slower.
01-18 20:07:30.587 4264-4264/com.testapp.demo V/FA: Deferring to Google Analytics for Firebase for event data collection. https://goo.gl/J1sWQy
01-18 20:07:30.597 4264-4300/com.testapp.demo W/art: Class com.google.android.gms.dynamite.DynamiteModule failed lock verification and will run slower.
01-18 20:07:30.600 4264-4264/com.testapp.demo W/art: Class android.support.v4.util.SimpleArrayMap failed lock verification and will run slower.
01-18 20:07:30.629 4264-4264/com.testapp.demo D/AndroidRuntime: Shutting down VM
01-18 20:07:30.632 4264-4264/com.testapp.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.testapp.demo, PID: 4264
    java.lang.NoSuchMethodError: No static method com_google_firebase_components_Lazy$$Lambda$1_lambda$new$0(Lcom/google/firebase/components/ComponentFactory;Lcom/google/firebase/components/ComponentContainer;)Ljava/lang/Object; in class Lcom/google/firebase/components/Lazy; or its super classes (declaration of 'com.google.firebase.components.Lazy' appears in /data/app/com.testapp.demo-1/base.apk)
        at com.google.firebase.components.Lazy$$Lambda$1.get(com.google.firebase:firebase-common@@16.0.4)
        at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-common@@16.0.4:54)
        at com.google.firebase.components.AbstractComponentContainer.get(com.google.firebase:firebase-common@@16.0.4:26)
        at com.google.firebase.components.ComponentRuntime.get(com.google.firebase:firebase-common@@16.0.4:34)
        at com.google.firebase.FirebaseApp.<init>(com.google.firebase:firebase-common@@16.0.4:540)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.0.4:355)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.0.4:324)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.0.4:310)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@16.0.4:53)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1758)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1733)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@16.0.4:47)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6326)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5918)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5857)
        at android.app.ActivityThread.-wrap3(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
01-18 20:07:30.697 4264-4300/com.testapp.demo I/DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:11020
    Selected remote version of com.google.android.gms.ads.dynamite, version >= 11020
01-18 20:07:30.698 4264-4300/com.testapp.demo V/DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
01-18 20:07:30.810 4264-4300/com.testapp.demo W/System: ClassLoader referenced unknown path: 
01-18 20:07:31.060 4264-4300/com.testapp.demo W/System: ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/0000006e/n/armeabi-v7a
    ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/0000006e/n/armeabi

**Comment by appadvisorydev** [comment]
> @appadvisorydev Your crash is related to [this thread](https://github.com/firebase/quickstart-unity/issues/271). This should only happen to 5.4.2 or later. We will release fix in the next release. At the meantime, you can remove the Firebase Plugin and install [Firebase 5.4.1](https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_5.4.1.zip).
> 
> @youdk Could you try [Firebase 5.4.1](https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_5.4.1.zip) on your side? Let me see if I can repro the DllNotFound exception and the message crash on our end.

@chkuang-g Hi and thanks for your answer.

It's still happening with this version : 

`Native StackTrace:

Thread 0 (crashed)
0   /var/containers/Bundle/Application/0255BF10-22F4-4A0F-80E2-FDA6EC2D4D40/inthetarget.app/inthetarget0x000000010456ff6c InterfaceFuncInvoker0<int>::Invoke(unsigned int, Il2CppClass*, Il2CppObject*) 
1   /var/containers/Bundle/Application/0255BF10-22F4-4A0F-80E2-FDA6EC2D4D40/inthetarget.app/inthetarget0x00000001059e2578 FirebaseLogger_LogMessage_mEF2033A0588D651D162FFE29C9FA77A39E51233E 
2   /var/containers/Bundle/Application/0255BF10-22F4-4A0F-80E2-FDA6EC2D4D40/inthetarget.app/inthetarget0x0000000104572e98 ReversePInvokeWrapper_FirebaseApp_LogMessage_mA9E891D35AE230C0F45350F65E3460030ACC2A48 
3   /var/containers/Bundle/Application/0255BF10-22F4-4A0F-80E2-FDA6EC2D4D40/inthetarget.app/inthetarget0x00000001057b500c firebase::AppLogCallback(firebase::LogLevel, char const*, void*) 
4   /var/containers/Bundle/Application/0255BF10-22F4-4A0F-80E2-FDA6EC2D4D40/inthetarget.app/inthetarget0x000000010578f00c firebase::LogMessageWithCallbackV(firebase::LogLevel, char const*, char*) 
5   /var/containers/Bundle/Application/0255BF10-22F4-4A0F-80E2-FDA6EC2D4D40/inthetarget.app/inthetarget0x000000010578f0ac firebase::LogWarning(char const*, ...) 
6   /var/containers/Bundle/Application/0255BF10-22F4-4A0F-80E2-FDA6EC2D4D40/inthetarget.app/inthetarget0x00000001057b5c4c firebase::CppInstanceManager<firebase::App>::~CppInstanceManager() 
7   /usr/lib/system/libsystem_c.dylib  0x00000001eab63ab4 __cxa_finalize_ranges 
8   /usr/lib/system/libsystem_c.dylib  0x00000001eab63dd8 exit 
9   /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore0x000000021827c670 -[UIApplication terminateWithSuccess] 
10  /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore0x0000000217b110d4 __98-[__UICanvasLifecycleMonitor_Compatability deactivateEventsOnly:withContext:forceExit:completion:]_block_invoke.279 
11  /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore0x0000000218280cd0 _runAfterCACommitDeferredBlocks 
12  /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore0x000000021826eccc _cleanUpAfterCAFlushAndRunDeferredBlocks 
13  /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore0x000000021829dfa0 _afterCACommitHandler 
14  /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation0x00000001eb0037a8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ 
15  /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation0x00000001eaffe43c __CFRunLoopDoObservers 
16  /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation0x00000001eaffe9dc __CFRunLoopRun 
17  /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation0x00000001eaffe1cc CFRunLoopRunSpecific 
18  /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices0x00000001ed275584 GSEventRunModal 
19  /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore0x0000000218275054 UIApplicationMain 
20  /var/containers/Bundle/Application/0255BF10-22F4-4A0F-80E2-FDA6EC2D4D40/inthetarget.app/inthetarget0x000000010454beb0 main 
21  /usr/lib/system/libdyld.dylib      0x00000001eaabebb4 start `

**Comment by appadvisorydev** [comment]
@chkuang-g here another stack trace : 

Remote Config: Fetch encountered an error: No se ha podido completar la operación. (Error de com.google.remoteconfig.ErrorDomain 8003.)   at GameAnalyticsSDK.Events.GA_Debug.HandleLog (System.String logString, System.String stackTrace, UnityEngine.LogType type) <0x00000 + 0xffffffff> 0 in <00000000000000000000000000000000>:0    at UnityEngine.Application.CallLogCallback (System.String logString, System.String stackTrace, UnityEngine.LogType type, System.Boolean invokedOnMainThread) <0x00000 + 0xffffffff> 0 in <00000000000000000000000000000000>:0

**Comment by tholmgren** [comment]
Hi, I'm also having this issue but can't replicated it. Two questions. Does anyone know if the user is aware of the crash? 2) Is there an ETA for the update with the fix? Thanks.

**Comment by appadvisorydev** [comment]
> Hi, I'm also having this issue but can't replicated it. Two questions. Does anyone know if the user is aware of the crash? 2) Is there an ETA for the update with the fix? Thanks.

Impossible to replicate on my side. I don't know where happens this crash... it's anxiety.

**Comment by chkuang-g** [comment]
@appadvisorydev This is odd.  This should not happens to 5.4.1.  But anyway.  We released [latest 5.4.4 release](https://firebase.google.com/download/unity) which should fix your crash at CppInstanceManage.  Also, you seems experiencing error in Remote Config as well.  I would suggest to completely remove the Firebase Plugins (those from Assets/Plugins/ and Assets/Firebase/ folder) and reinstall everything again.

@tholmgren There are two different crashes here, one related to messaging and another to CppInstanceManager.  Which one are you talking about?  If it is the latter one, please upgrade to [latest 5.4.4 release](https://firebase.google.com/download/unity).  If it is the former one, could you provide more detail in your environment, ex. Unity version, Firebase version, plugin you used, etc.? 

@youdk Regarding to your crash at FirebaseApp.initializeApp and DllNotFound exception, what is the **Scripting Runtime Version** in your Player Setting (Edit > Project Setting > Player > Other Settings)?  When you import Firebase plugin, did you import from **dotnet3** or **dotnet4** folder?

Shawn

**Comment by youdk** [comment]
> @appadvisorydev This is odd. This should not happens to 5.4.1. But anyway. We released [latest 5.4.4 release](https://firebase.google.com/download/unity) which should fix your crash at CppInstanceManage. Also, you seems experiencing error in Remote Config as well. I would suggest to completely remove the Firebase Plugins (those from Assets/Plugins/ and Assets/Firebase/ folder) and reinstall everything again.
> 
> @tholmgren There are two different crashes here, one related to messaging and another to CppInstanceManager. Which one are you talking about? If it is the latter one, please upgrade to [latest 5.4.4 release](https://firebase.google.com/download/unity). If it is the former one, could you provide more detail in your environment, ex. Unity version, Firebase version, plugin you used, etc.?
> 
> @youdk Regarding to your crash at FirebaseApp.initializeApp and DllNotFound exception, what is the **Scripting Runtime Version** in your Player Setting (Edit > Project Setting > Player > Other Settings)? When you import Firebase plugin, did you import from **dotnet3** or **dotnet4** folder?
> 
> Shawn

@chkuang-g Unity setting is .NET 3.5, we imported firebase from "dotnet3" folder.

**Comment by stewartmiles** [comment]
I've spent some more time digging into this and discovered a couple of ways the current code can crash.  Firstly, I'll provide some background on how the SDK works then it may make a bit of sense.

In the FCM (Firebase Cloud Messaging) C++ & Unity SDK on Android we have a C#/C++ component that links with your application code and runs when the Android activity starts and an [Android service](https://developer.android.com/guide/components/services) that handles token registration, change events and messages.  The Android service is required as messages can be received when the Activity isn't running or even loaded into memory.  Since the Android service is another process and runs independently of the activity we need a way to communicate from the service to the activity.  To perform this communication write events into a file in the application's local storage that are read by the Activity when it eventually gets to run.  So the typical flow is:

- FCM event received by device (Google Play services APK / daemon handles this)
- FCM event received by FCM service shipped with your app
- FCM service writes to an FCM event file.
- When the Activity runs it reads events from the FCM event file and clears it waiting for new events.

If you're _really_ interested we use [FlatBuffers](https://google.github.io/flatbuffers/) - which we help maintain - (see https://twitter.com/wvo/status/1080512145794654208) to encode data in this event file.

Now the issues I found were:
- If the device runs out of space the code that parses the FCM event file can page fault if the file is truncated.
- If the FCM event file is corrupted (e.g very rare flash bit flip) the event validation failed parsing continued which could again result in a page fault.

So I now have a patch lined up which I *think* will fix this issue (fingers crossed) though it's very hard to reproduce on device as the page fault will only happen if the buffer used to read the file ends up at the end of a memory page.

**Comment by tholmgren** [comment]
> @appadvisorydev This is odd. This should not happens to 5.4.1. But anyway. We released [latest 5.4.4 release](https://firebase.google.com/download/unity) which should fix your crash at CppInstanceManage. Also, you seems experiencing error in Remote Config as well. I would suggest to completely remove the Firebase Plugins (those from Assets/Plugins/ and Assets/Firebase/ folder) and reinstall everything again.
> 
> @tholmgren There are two different crashes here, one related to messaging and another to CppInstanceManager. Which one are you talking about? If it is the latter one, please upgrade to [latest 5.4.4 release](https://firebase.google.com/download/unity). If it is the former one, could you provide more detail in your environment, ex. Unity version, Firebase version, plugin you used, etc.?
> 
> @youdk Regarding to your crash at FirebaseApp.initializeApp and DllNotFound exception, what is the **Scripting Runtime Version** in your Player Setting (Edit > Project Setting > Player > Other Settings)? When you import Firebase plugin, did you import from **dotnet3** or **dotnet4** folder?
> 
> Shawn

@chkuang-g 

My app is live and I'm not seeing any crashes.   Thank you for following up!  
Have a great weekend.

**Comment by jonsimantov** [comment]
@youdk Did you determine if upgrading to a newer version (the current version is Firebase Unity 5.4.4) fixes the crash you were seeing?

**Comment by MiketoString** [comment]
We have an application using 5.4.4 that just went live and are seeing the "firebase::messaging::ProcessMessages()" crash in Crashlytics.  Appears to be a small percent of userbase, but crash happened for a new install.

```
Caused by java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 1281177f
Build fingerprint: 'samsung/gvwifiue/gvwifiue:5.1.1/LMY47X/T670UEU2APJ1:user/release-keys'
Revision: 'unknown'
pid: 23114, tid: 24120, name: Thread-142489  >>> com.mycompany.game <<<
    r0 d16a908c  r1 1281177f  r2 5e384001  r3 c59ffa74
    r4 d16a908c  r5 f6fb5df4  r6 cee58c00  r7 00000010
    r8 d1609084  r9 c59ffaf1  sl c59ffb10  fp c59ffba0
    ip f6fac6dc  sp c59ffa80  lr cedab32f  pc cedac1b2  cpsr f47fdb30

       at libFirebaseCppApp-5.000ed1b2(Unknown Source)
       at libFirebaseCppApp-5.firebase::messaging::ProcessMessages()(messaging:1726)
       at libFirebaseCppApp-5.000ec9e7(Unknown Source)
       at libc.__pthread_start(void*)(__pthread_start:30)
       at libc.__start_thread(__start_thread:6)
```

**Comment by youdk** [comment]
> @youdk Did you determine if upgrading to a newer version (the current version is Firebase Unity 5.4.4) fixes the crash you were seeing?

We have tried on 5.4.1 and the crash also happened. 
chkuang-g suggested me to use firebase 5.4.1 instead of 5.4.4.

**Comment by youdk** [comment]
@chkuang-g Is there any progress on this issue?

**Comment by stewartmiles** [comment]
@youdk my patch was applied in 5.4.4, the issue should be fixed.  Please let us know if it isn't when upgrading to 5.4.4.

**Comment by hoadn** [comment]
> @youdk my patch was applied in 5.6.0, the issue should be fixed. Please let us know if it isn't when upgrading to 5.6.0.

I am using 5.6.0, this problem still happen. When using script backend is Mono, the android app working fine. But when using the IL2CPP, it's force close. I am import the dotnet3 folder

> 2019-05-07 10:52:30.940 11118-11140/? E/CRASH: 	#03  pc 00105b09  /data/app/com.mygame.example-thiOv_hD_MJZ2gP4PBxhNg==/lib/arm/libFirebaseCppApp-5.6.0.so (firebase::LogAssert(char const*, ...)+18)

**Comment by stewartmiles** [comment]
@hoadn could you share the complete stack trace for the crash you're seeing?  The snippet of the stack you shared doesn't appear to line up with the original bug report.

**Comment by stewartmiles** [comment]
@hoadn any updates?

**Comment by stewartmiles** [comment]
@hoadn since we haven't heard from you we'll assume the issue is resolved.  Let us know if you have the complete stack trace to share if it comes up again.
