### ISSUE TITLE
Errors in importing Firebase sdk package in unity

### ISSUE THREAD

**Issue by swats1010** [firebase/quickstart-unity#622]
### Please fill in the following fields:
Unity editor version: 2017.4.12f 1 personal 
Firebase Unity SDK version: 6.13.0
Firebase plugins in use (Auth, Database, etc.): Analytics and RemoteConfig
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, PlayFab, ChatBoost, GoogleMobileAds and AudienceNetwork
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Mac
Platform you are targeting (iOS, Android, and/or desktop):  Android
Scripting Runtime (Mono, and/or IL2CPP):Mono

### Please describe the issue here:
I downloaded the firebase unity package  and imported the analytics and remoteconfig unity firebase package in the unity and then got these many error . I imported the dotnet3 version of the unity packages ...
There are 850+ errors and the error logs says so : 
```

MissingMethodException: Method not found: 'Google.EditorMeasurement.set_InstallSourceFilename'.
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Firebase.Editor.Measurement
Firebase.Editor.AndroidSettingsChecker..cctor () (at Z:/tmp/tmp.SHkOPK7iEJ/firebase/app/client/unity/editor/src/AndroidAPILevelChecker.cs:37)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Firebase.Editor.AndroidSettingsChecker
System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor (RuntimeTypeHandle type) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.CompilerServices/RuntimeHelpers.cs:101)
UnityEditor.EditorAssemblies.ProcessEditorInitializeOnLoad (System.Type type) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:136)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoCMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:519)
System.Reflection.MonoCMethod.Invoke (BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:528)
System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/ConstructorInfo.cs:77)
System.Activator.CreateInstance (System.Type type, Boolean nonPublic) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Activator.cs:372)
System.Activator.CreateInstance (System.Type type) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Activator.cs:254)
UnityEditor.AssetPostprocessingInternal.GetTextureProcessorVersions () (at /Users/builduser/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:309)
UnityEditor.AssetDatabase:Refresh()
GooglePlayServices.<ResolveUnsafe>c__AnonStorey21:<>m__42(Boolean, String) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1753)
GooglePlayServices.<ResolveUnsafe>c__AnonStorey21:<>m__4C() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1791)
Google.RunOnMainThread:ExecuteNext() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:377)
Google.RunOnMainThread:<ExecuteAll>m__A() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:408)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
Google.RunOnMainThread:Run(Action, Boolean) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:363)
GooglePlayServices.<ResolveUnsafe>c__AnonStorey21:<>m__44() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1790)
GooglePlayServices.<DoResolution>c__AnonStorey13:<>m__29() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/GradleResolver.cs:713)
GooglePlayServices.<DoResolutionUnsafe>c__AnonStorey14:<>m__1F(List`1) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/GradleResolver.cs:761)
GooglePlayServices.<GradleResolution>c__AnonStoreyF:<>m__16() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/GradleResolver.cs:318)
GooglePlayServices.<GradleResolution>c__AnonStoreyF:<>m__24() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/GradleResolver.cs:383)
GooglePlayServices.<ProcessAars>c__AnonStorey17:<>m__21() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/GradleResolver.cs:1011)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:300)
Google.RunOnMainThread:<ExecuteAll>m__A() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:414)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

```

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? 
I tried adding the quickstart project , but there are different kinds of errors in that projects but not these errors which i faced in my own project 

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by alexames** [comment]
Is there a reason you imported dotnet3 instead of dotnet4? Unity 2017.x and later allow the use of the .NET 4.x framework. If your Unity project uses .NET 4.x, import the dotnet4/ package.

**Comment by NikolayVoronkov** [comment]
Same issue with 6.13.0, import dotnet4 messaging package in 2019.2.18f. 6.12.0 work fine.

**Comment by chkuang-g** [comment]
Seems like `Firebase.Editor.dll` cannot find `Google.EditorMeasurement`, which is a new class in the new version of External Dependency Manager (EDM), which was renamed from Play Services Resolver.

If you are unable to build, here is what you can do:

1. Find the folders named `ExternalDependencyManager` and `PlayServicesResolver` under your `Assets` folder.  Remove them.
1. Download the latest [EDM](https://github.com/googlesamples/unity-jar-resolver/raw/master/external-dependency-manager-latest.unitypackage) and import it.
1. Wait a bit
    1. If you are building for Android, when you switch platform to Android,  you should see AndroidResolver window kick-in.  If not, check your settings under `Assets > External Dependency Manager > Android Resolver > Settings` and see if `Enable Auto-Resolution` is on.  Or you can force resolution using `Assets > External Dependency Manager > Android Resolver > Force Resolve`
    1. If you are building for iOS, make sure that iOS Resolver is enabled by checking settings under `Assets > External Dependency Manager > iOS Resolver > Setting`.  `Podfile Generation` should be checked.

Let me know if it helps.

**Comment by gabetoth-dgh** [comment]
@NikolayVoronkov Where can I download 6.12.0?

**Comment by gabetoth-dgh** [comment]
I could get 6.12.0, that works fine.

**Comment by roointan** [comment]
@chkuang-g I was having this issue, and what you said helped progress,
But now I have this issue:
https://github.com/firebase/quickstart-unity/issues/619

I feel like being in a loop :)

**Comment by roointan** [comment]
Any older version of Firebase package for Unity which doesn't depend on Google.EditorMeasurement.set_InstallSourceFilename and I could use in the mean time while this is fixed?

**Comment by Jacowaco** [comment]
I have the same issue

**Comment by pruthvi** [comment]
Initially, I too thought that I'm doing some mistake in my build setting. Cleaned up my project thrice now from last 2 days, error still persist. 

Unity editor version: 2019.3.7f 1 personal
Firebase Unity SDK version: 6.13.0
Firebase plugins in use: Auth
Additional SDKs you are using: GooglePlayServices
Platform you are using the Unity editor on : Windows
Platform you are targeting : Android
Scripting Runtime : IL2CPP
Using NET 4.x framework in project and unity package from Firebase_Unity_SDK/dotnet4
Also, tried Play Services Resolver and even changed Android API Levels in player setting but nothing works.

Error:
```
System.TypeInitializationException: The type initializer for 'Firebase.Editor.Measurement' threw an exception. ---> System.MissingMethodException: void Google.EditorMeasurement.set_InstallSourceFilename(string)
   --- End of inner exception stack trace ---
  at Firebase.Editor.AndroidSettingsChecker..cctor () [0x0000c] in Z:\tmp\tmp.SHkOPK7iEJ\firebase\app\client\unity\editor\src\AndroidAPILevelChecker.cs:37 
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[])
```

**Comment by patm1987** [comment]
To be clear both @Jacowaco and @pruthvi:

- Are you using the 6.13.0 plugin
- From the *.unitypkg (as opposed to installing them with the Unity Package Manager)
- did you follow the steps from @chkuang-g by:
- - Deleting anything called `ExternalDependencyManager` 
![image](https://user-images.githubusercontent.com/1111611/79163988-55244800-7d9d-11ea-8d64-dcd9efa24df1.png)
- - And Deleting anything called `PlayServicesResolver` 
![image](https://user-images.githubusercontent.com/1111611/79164335-16db5880-7d9e-11ea-9930-867bb85e6c2e.png)
- - _then_ installing the [most recent version](https://github.com/googlesamples/unity-jar-resolver/raw/master/external-dependency-manager-latest.unitypackage) of [EDM4U](https://github.com/googlesamples/unity-jar-resolver)

> Note that this does not mean that you need to manage Firebase Unity with the Unity Package Manager. Just that you need to have the latest version of the External Dependency Manager for Unity with the latest Firebase Unity SDK.

If this all holds true, the next ask would be that you reproduce this in one of the quickstarts (such as the [Analytics](https://github.com/firebase/quickstart-unity/tree/master/analytics/testapp) one). If you run into a separate issue as @swats1010 mentioned, make sure you follow the README steps for your quickstart (such as making sure you install the Firebase SDK separately, since it doesn't ship as part of the quickstart). Once we have confirmation of your environment, the error you experience, and steps to reproduce in the quickstart we can quickly iterate on a patch to whatever issue you're experiencing!

I really feel bad about seeming so pedantic, but we really want to fix whatever issue you're having. These steps just are a way to ensure that we can find the exact issue that you're experiencing, fix it, and ensure that the fix doesn't regress in the future!

--Patrick

**Comment by jsebas8** [comment]
Hello everyone, I had the same error message of @pruthvi with database package, but I followed @chkuang-g and now it´s solved.

Thanks @chkuang-g and @patm1987 .
