### ISSUE TITLE
Messaging doesn't run stably on iOS 14

### ISSUE THREAD

**Issue by RafalPucilowski** [firebase/quickstart-unity#790]
* Unity editor version: 2019.3.12f1
  * Firebase Unity SDK version: 6.15.2
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Messaging
  * Other Firebase Components in use: none
  * Additional SDKs you are using: Agora Engine
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

Since the realase of iOS 14 we noticed problems with the operation of the messaging module. We are using it to send informations beetwen two users in our application that share the view from the camera on the back of the mobile device.

The problem manifests itself in such a way that messages do not always reach the addressee, even though no errors are recorded throughout the process. Sometimes everything works fine and the next time you connect to the user, it "hangs up" after a few sent messages. Sometimes messages doesn't arrive in the initial phase when an attempt is made to connect to the other user.

This issue only occure on iOS 14, application is working fine on the device with iOS system lower then 14 and on devices with Android system.

We will be grateful for advice on how to improve the stability of the messaging module under iOS.

**Comment by patm1987** [comment]
HI @RafalPucilowski ,

Thanks for sending a report in. Can I have you do a few things:
First, you left out a few fields in the bug report template that would really help. Can you tell us:
> Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
> What's the issue repro rate? (eg 100%, 1/5 etc)

Getting accurate (>50%) repro steps in the [sample app for messaging](https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp) will help us get to the source of the issue as fast as possbile!

Second: Can you send us some sample code to see exactly what you're trying to do? It sounds like you might be running into issues with [Upstream Messages](https://firebase.google.com/docs/cloud-messaging/unity/upstream) but it'd be great to see the firebase bits to verify everything looks right at first glance.

**Comment by RafalPucilowski** [comment]
Hi @patm1987,

thank you very much for your reply.

About first question, we didn't try to reproduce the issue on the Firebase Unity quickstart project because we use the backend to send messages. I should have mentioned this earlier, for which I am sorry. The whole process looks something like that: when user A wants to send a message to user B, it sends UnityWebRequest on the backend (all the required data are included in this request), which then sends a notification to the appropriate user via Firebase. The issue seems to be a problem with receiving messages, but I think we can't rule out the possibility that the sending is failing for some reason.

About second question, it's hard to say. It gives the impression that the message or data limit is running out. So at the app start it is fine but at some point the messages stop coming, after some time everything returns to normal (as if the limit was restarted) and the whole cycle repeats. If I had to define the rate, I would say 50%.

I will talk to our web developer and client today (to make sure they don't mind sharing the code) and we will try to prepare a sample code for you to check.

Have a great day.

**Comment by patm1987** [comment]
Note that if it makes you feel more comfortable, you can always [file a bug report](https://firebase.google.com/support/troubleshooter/report/bugs). This will go through an internal process which would help keep your code secret and the support agents there may be able to examine your project setup to see if there's anything obviously wrong. If you go that route, feel free to link this GitHub issue in your report!

**Comment by RafalPucilowski** [comment]
Hi,
sorry for the silence on our side but it's been a very busy week for me on other projects. We were able to contact the client and he agreed to try to reproduce the bug in your quickstart project and share the code from the main application.

I also talked to a colleague who was the original developer of the application and it turns out that due to latency only some types of messages are sent through our backend and so far we have not noticed that they cause any problems. So, only those sent via Cloud Messaging cause issue.

Below is one of the methods that cause trouble:

> private void SendChangeCameraFreezeStateRequest ()
> {
> 	MessageDataBase messageData = new MessageDataBase("changeCameraFreezeState", Time.realtimeSinceStartup);
> 	BasicMessage message = new BasicMessage(
> 		"/topics/" + CallController.receiveCall.streamer,
> 		1,
> 		"high",
> 		messageData
> 	);
> 
> 	StartCoroutine(ChangeCameraFreezeStateRequest.POST(uri, headers, JsonUtility.ToJson(message)));
> }

uri is equal to "https://fcm.googleapis.com/fcm/send", and 2 headers are set:

key: Content-Type
value: application/json

and 

key: Authorization
value: here is our server key taken from the Firebase console

The POST method looks like this:

> public IEnumerator POST(string uri, Header[] headers, string body = null)
> {
>         byte[] data = null;
> 	if (body != null)
> 	{
> 		data = Encoding.UTF8.GetBytes(body);
> 	}
> 
>         using (UnityWebRequest unityWebRequest = UnityWebRequest.Post(uri, body))
>         {
> 		if (data != null && data.Length > 0)
> 		{
> 			unityWebRequest.uploadHandler = new UploadHandlerRaw(data);
> 		}
> 
>                 yield return Request(headers, unityWebRequest);
>         }
> }

and Request method looks like this:

> private IEnumerator Request(Header[] headers, UnityWebRequest unityWebRequest)
>  {
>         SetHeaders(headers, unityWebRequest);
>         yield return unityWebRequest.SendWebRequest();
>         CheckRequest(unityWebRequest);
>  }

below are two more methods used in Request()

> private void SetHeaders(Header[] headers, UnityWebRequest unityWebRequest)
> {
>         foreach (Header header in headers)
>         {
>             unityWebRequest.SetRequestHeader(header.Key, header.Value);
>         }
> }

> private void CheckRequest(UnityWebRequest unityWebRequest)
> {
>         if ((unityWebRequest.isNetworkError == true) || (unityWebRequest.isHttpError == true))
>         {
>             Fail(unityWebRequest);
>         }
>         else
>         {
>             Success(unityWebRequest);
>         }
> }

CheckRequest() invoke Success() at the end even when the news stops arriving.

If you see anything that may be causing this issues or have any questions please let me know. Next week we will try to do tests on your project. If we manage to reproduce the bug, we will probably do a bug report.

Thank you very much for your time.

**Comment by RafalPucilowski** [comment]
Hi @patm1987 ,
we reported a bug - case 00089714 - with video and simple project.
Looking forward for your findings.

**Comment by chkuang-g** [comment]
Hi @RafalPucilowski 

Where can we find the video and simple project for this case 00089714? Did you report it through a different channel?

FWIW, could you try the latest `6.16.0` and see if the instability is resolved, since the Pod version was upgraded from `6.24.0` to `6.32.2`.

I also noticed this weird issue with push notification #820 and was trying to reach out to FCM team about this.

Please let us know if upgrading works for you.

Shawn

**Comment by RafalPucilowski** [comment]
Hi Shawn,

we send the Bug Report but the issue is still not resolved. Right now we will be checking if the latest iOS update has changed anything.
Regarding your suggestion, we used the 6.16.0 in test project.

Bellow is the link to the video and the description what to look for.

https://drive.google.com/file/d/1gxd_jTIhnyVXeX82d9doAQciiiYyvyxu/view?usp=sharing

Phones from left:
- iPhone 7 (iOS 13.4.1)
- iPhone 8 (iOS 13.3)
- **iPhone XS (iOS 14.0.1)**
- Samsung Galaxy S7 (Android 8.0)

The flow of the application is very simple, it attach to a message event, joins the room, and increases the counter when it receives any message. Of course all devices runs the same application. You can see that all devices receive messages (on iOS sometimes one message appears 3 times) but only counter on the iPhone XS stops at some point.

I will find out if we still have a project available online and send it to you later.

If you have any thoughts on that issue, please let me know.
Rafal

**Comment by RafalPucilowski** [comment]
Hi,

here is the link to the test project:
https://drive.google.com/file/d/1vcqc3FgE_b3Ccmtcedl1us4Kt0C8oxc0/view?usp=sharing

Just find the Manager object in the scene and set the Authorization key and you should be able to build and run the app.

Let me know when you reproduce the problem.
Rafal

**Comment by patm1987** [comment]
Definitely let us know here if you make any progress in the bug report.

I have some more things for you to try:
1) can you try 6.16.1 just to see if anything there fixed your issue?
2) Can you gather debug logs with `-FIRDebugEnabled` [set as an argument](https://help.apple.com/xcode/mac/8.0/#/dev3ec8a1cb4)?
3) I assume that you have since this is iOS 14 specific, but have you [uploaded your APNs certificate/auth key](https://firebase.google.com/docs/cloud-messaging/ios/certs)?
4) Is swizzling enabled (ie: things may fail if you explicitly disable it in your `Info.plist`. If you don't know what this is then you should be good)
5) Can you reproduce this issue by [directly sending messages via APNs](https://firebase.googleblog.com/2017/01/debugging-firebase-cloud-messaging-on.html)?

**Comment by patm1987** [comment]
A quick update, I did some digging over the weekend and found that there were some token generation issues that were fixed recently (an example issue: https://github.com/firebase/firebase-ios-sdk/issues/6862 ).

That particular bug looks like it might have been fixed in `7.0.0` and the Firebase Unity SDK ships with the iOS pod at version `6.32.2` with Unity SDK `6.16.1`. I'd still recommend upgrading to the latest SDK then, if that doesn't work, locate your `MessagingDependencies.xml` file and change the line:
```
<iosPod name="Firebase/Messaging" version="6.32.2" minTargetSdk="8.0">
```

to:
```
<iosPod name="Firebase/Messaging" version="7.0.0" minTargetSdk="8.0">
```

to see if that works.

An important note: the Unity SDK is typically pinned to a specific iOS SDK. Modifying this field will put you into an unsupported configuration, until a new version of the Unity Firebase SDK is released. This may work, but only do this if it fixes your issue and do some extra testing around messaging.

**Comment by RafalPucilowski** [comment]
Hi @patm1987 

thank you very much for your time spent on the issue. We conducted tests on our other project, that is during development, which also uses Firebase communication for iOS, and also on the test project, and I can confirm that the issue has not occurred so far.

By the end of the week, I will update the Unity SDK on my project and change the iOS pod to 7.0.0. 
Everything indicates that we will finally be able to end this thread 👍

**Comment by chkuang-g** [comment]
Hi @RafalPucilowski ,

Any update from your side?

**Comment by RafalPucilowski** [comment]
Hi @chkuang-g,

I got some update. Our QA spend couple of hours on testing application with suggested setup (Unity SDK 6.16.1 and iOS pod 6.32.2). 

He wasn't able to use iOS pod 7.0.0 because as far as I can remember, the app was unstable and there were crashes.
Fortunately it works much better with iOS pod 6.32.2.

We tested the connection between two iPhone devices (on system versions 13.4 and 14.2), which was stable and did not lose any messages sent. 

Unfortunately, problems appeared when trying to use the device on Android. Our tester was unable to run the build. Immediately at the start there was a crash and this error:

`2020-11-20 12:47:16.005 21754-21754/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ForExperience.Ar4Vision, PID: 21754
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.ForExperience.Ar4Vision/com.google.firebase.MessagingUnityPlayerActivity}: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.MessagingUnityPlayerActivity" on path: DexPathList[[zip file "/data/app/com.ForExperience.Ar4Vision-yLF_UXMkFQo8gz2SCosX0Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.ForExperience.Ar4Vision-yLF_UXMkFQo8gz2SCosX0Q==/lib/arm64, /data/app/com.ForExperience.Ar4Vision-yLF_UXMkFQo8gz2SCosX0Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3020)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.MessagingUnityPlayerActivity" on path: DexPathList[[zip file "/data/app/com.ForExperience.Ar4Vision-yLF_UXMkFQo8gz2SCosX0Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.ForExperience.Ar4Vision-yLF_UXMkFQo8gz2SCosX0Q==/lib/arm64, /data/app/com.ForExperience.Ar4Vision-yLF_UXMkFQo8gz2SCosX0Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3008)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) `

Finally, I shared my last build with him (which used the last Unity SDK). I remember having the same problems when I built it, but I believe changing the Player settings in Unity helped. Surprisingly, this time using the same settings did not help.

The connection between iPhone with iOS14.2 and Samsung S8 (possibly with the latest Android) was stable for the first 5 minutes of testing. Later on, the same issues with not arriving messages surfaced (interestingly, we haven't noticed this issue in cross-platform communication so far).

Then we checked the iPhone connection again and here too there was a problem. After further testing, we found that after restarting both applications, the iPhones could communicate stably with each other again.

Everything indicates that as long as there is no communication between different platforms (iOS <-> Android), sending and receiving messages works stably.

**Comment by DellaBitta** [comment]
Hi @RafalPucilowski,

6.16.* builds of the Firebase Unity SDK was tested and built with Pods older than Firebase iOS SDK 7.0.0, so the instability that you mentioned is expected. Forutnately we released [Firebase Unity SDK 7.0.0 and 7.0.1](https://firebase.google.com/support/release-notes/unity) which do use Firebase iOS SDK 7.0.0.  Could you try to update to the latest Unity SDK and try again?

Thanks!

**Comment by RafalPucilowski** [comment]
Hi @DellaBitta,

thanks for the update, we definitely will check new Unity SDK and let you know if issue is still present.
Best regards.
