### ISSUE TITLE
Firebase FacebookAuthProvider fails to sign in if using Facebook Gaming Graph. 

### ISSUE THREAD

**Issue by ferretnt** [firebase/quickstart-unity#826]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.11
  * Firebase Unity SDK version: 15.2
  * Source you installed the SDK: UPM (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Auth (Auth, Database, etc.)
  * Other Firebase Components in use: RTDB (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: Mono (Editor), il2cpp (Device) (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

We have updated one of our development apps to use the gaming graph. Login to facebook (using Facebook APIs) works correctly, and returns an access token of the form "GG|{tokenString}". Attempting to pass this token to SignInWithCredentialAsync() results in: 

     ---> (Inner Exception #0) Firebase.FirebaseException: The supplied auth credential is malformed or has expired.<---

     We can confirm that that token is for the gaming graph API (by logging the Facebook AccessToken's GraphDomain) , however, when we attempt to log in to Firebase using that token, SignInWithCredentialAsync() throws an exception , the inner of which is:

 "---> (Inner Exception #0) Firebase.FirebaseException: The supplied auth credential is malformed or has expired.<---"

Interestingly, Credential.IsValid() returns true. 

We are as certain we've got this test right as it's possible to be when most of the opportunities for error are mostly app configuration dashboards rather than the 10 lines of fairly well tested code itself.

Relevant code: 

Debug.Log($"Getting credential from access token {AccessToken.CurrentAccessToken.TokenString}");
Firebase.Auth.Credential credential = Firebase.Auth.FacebookAuthProvider.GetCredential(AccessToken.CurrentAccessToken.TokenString);
Debug.Log($"Credential has provider {credential.Provider} : IsValid {credential.IsValid()}" + credential.ToString());
var authTask = auth.SignInWithCredentialAsync(credential);

Debug.Log("Android debugging with printf is fun.");

try
{
    var authUser = await authTask;
    Debug.Log($"Firebase auth sign in task completed. IsCompleted:{authTask.IsCompleted} IsCanceled:{authTask.IsCanceled}. UserID {authUser.UserId} Provider: {authUser.ProviderId}");
}
catch (System.Exception ex)
{
...

#### Steps to reproduce:

* Produce a simple app with Firebase and Facebook SDKs. 
* Confirm that sign in with Facebook and Firebase Auth FacebookCredentialProvider works. 
* Switch facebook app in the Facebook developer dashboard to use Gaming Graph API
* https://www.facebook.com/fbgaminghome/developers/gaming-services/
* Confirm that Facebook will still sign in correctly but Firebase SignInWithCredentialAsync logs exception: 

---> (Inner Exception #0) Firebase.FirebaseException: The supplied auth credential is malformed or has expired.<---

Repro 100%

**Comment by chkuang-g** [comment]
Hi @ferretnt 

Firebase currently only support regular Facebook Login but not this separate login for gaming.

I can file a feature request for you.  Since this will requires some backend changes, it probably will not be done soon.

Another option is to configure a generic OIDC provider by upgrading to GCIP.
https://cloud.google.com/identity-platform/docs/web/oidc
And you can use [OAuthProvider](https://firebase.google.com/docs/reference/unity/class/firebase/auth/o-auth-provider) to sign-in with Firebase Auth SDK.
```
var credential = Firebase.Auth.OAuthProvider.GetCredential("oidc.myProvider", idToken, accessToken);
var task = auth.SignInWithCredentialAsync(credential);
```

They have a different billing structure though since it charges a small amount per MAU.

**Comment by chkuang-g** [comment]
Internal feature request tracking: b/171089917

**Comment by tylerfangfb** [comment]
@chkuang-g Dev of Facebook Login for Gaming here. I'd love to help making Facebook Login for Gaming compatible with Firebase. We have developer reported the following exception:

--- 
The supplied auth credential is malformed or has expired. [ Remote site 5XX from facebook.com for VERIFY_CREDENTIAL ]
---

All I need to know is how FireBase verifies credential with Facebook. Could you help?

**Comment by jsding** [comment]
Any news on this FR? There is no official way to move Face Gaming Login to Facebook login, so we not able to use Facebook in our app now.

Thanks

**Comment by ferretnt** [comment]
I filed a corresponding issue to this one on the Facebook sdk GitHub at the
time (?? 12 months ago??) as this issue if that is helpful for info.

All our current development is enterprise with azure auth so not able to
provide any further information in the short term, sorry.

**Comment by yansievre** [comment]
> Hi @ferretnt
> 
> Firebase currently only support regular Facebook Login but not this separate login for gaming.
> 
> I can file a feature request for you. Since this will requires some backend changes, it probably will not be done soon.
> 
> Another option is to configure a generic OIDC provider by upgrading to GCIP. https://cloud.google.com/identity-platform/docs/web/oidc And you can use [OAuthProvider](https://firebase.google.com/docs/reference/unity/class/firebase/auth/o-auth-provider) to sign-in with Firebase Auth SDK.
> 
> ```
> var credential = Firebase.Auth.OAuthProvider.GetCredential("oidc.myProvider", idToken, accessToken);
> var task = auth.SignInWithCredentialAsync(credential);
> ```
> 
> They have a different billing structure though since it charges a small amount per MAU.

Hi, I was wondering if you were able to accomplish this. From what I found out, I need to use LoginWithTrackingPreference to produce an AuthenticationToken (which I think is what is needed for the idToken parameter of the GetCredential function) but this only works on iOS.

**Comment by yanmasharski** [comment]
It would be great to have this feature, lot of games use FB & Firebase.

**Comment by jsding** [comment]
> Hey everyone, just want to let you know that I've worked with the team at FireBase to investigate the issue. A fix is expected in coming weeks. Thank you all for your patience and we hope to resolve this long standing issue as soon as we can.

Any progress regarding about this issue?

Thanks

**Comment by nonstappstudio** [comment]
Do we have any progress on that? Thanks for the reply :)

**Comment by tylerfangfb** [comment]
A fix has been deployed by team @ google. Could someone who ran into this issue before try again?

**Comment by bombayplayinc** [comment]
Hi @tylerfangfb. We tried after the update. Now the error we are seeing is this:
```
Remote site 5XX from facebook.com for USER_INFO
```
Do we need to update the Firebase sdk also?

**Comment by 452283662** [comment]
I updated firebase to the latest version and this problem still exists.
The error is "Remote site 5XX from facebook.com for USER_INFO"

**Comment by arkon89games** [comment]
me too:  Firebase.FirebaseException: The supplied auth credential is malformed or has expired. [ Remote site 5XX from facebook.com for VERIFY_CREDENTIAL ] 

> I updated firebase to the latest version and this problem still exists. The error is "Remote site 5XX from facebook.com for USER_INFO"

**Comment by eatsports** [comment]
Hello, is there any updates about this issue?

**Comment by Ant1m3ta** [comment]
This issue happens in Firebase SDK 8.8.0 as well.

**Comment by rainbowcreatures** [comment]
After 2 days I discovered the above is why our newly implemented Facebook login over Firebase doesn't work...though I didn't test with Firebase 8.8.0 yet...any updates?

**Comment by GamecaveSD** [comment]
Still not working here with latest SDKs and nobody seems to care at all.
It's a complete disaster. You can't even add the old "Facebook Login" anymore, because something is bugged in the Facebook interface. When trying to add any package it always says "We couldn't find your developer website URL in your app's store listing", although it's there. Bug reports on Facebook also don't work...

**Comment by MetalMonkey-GSD** [comment]
Still not working here with latest SDKs and nobody seems to care at all.
It's a complete disaster. You can't even add the old "Facebook Login" anymore, because something is bugged in the Facebook interface. When trying to add any package it always says "We couldn't find your developer website URL in your app's store listing", although it's there. Bug reports on Facebook also don't work...

**Comment by krenki-fitonomy** [comment]
@tylerfangfb do you have any update on the issue? Have you managed to resolve it?
