### ISSUE TITLE
Deeplink not working. application:continueUserActivity:restorationHandler missing

### ISSUE THREAD

**Issue by moori** [firebase/quickstart-unity#86]
Hello
I'm trying follow the setup guides and implemented the deep link functionality on my Unity project. Android version is working fine, but on iOS I´m unable to retrieve the deeplink in my Unity code.
The app opens when I click on my link, either closed or running in background, and I can see the full url in Xcode console, but my OnInviteReceived inside Unity never runs. I get a "DEBUG: Found application:continueUserActivity:restoreHandler" followed by "Implementation of application:continueUserActivity:restorationHandler: not found. Please add the handler into your App Delegate. Class: UnityAppController"

I don´t know if its related, but I´m also unable to log any event on Analytics on iOS.

Am I missing something?

**Comment by stewartmiles** [comment]
We have root caused this issue and have fixed internally, we'll have a release with the fix soon.

Cheers,
Stewart

**Comment by stewartmiles** [comment]
We just published a fix for this https://firebase.google.com/support/release-notes/unity#4.0.0 please reopen if you continue to run into issues.

Cheers,
Stewart

**Comment by moori** [comment]
Thank you,

I´m now correctly receiving the deeplink when the app is already open.
Unfortunately, I´m still unable to retrieve it when I run the app by clicking in the custom url.

**Comment by stewartmiles** [comment]
To confirm, you're using the 4.0.0 SDK?  The issue we fixed was primarily in the Firebase iOS SDK 4.0.2 which the 4.0.0 SDK depends upon.

You should also verify you've setup the URL handlers in your Xcode project:

- applinks:YOUR_APP_BUNDLE_ID
- applinks:YOUR_DEEP_LINK_DOMAIN

e.g

- applinks:com.myneatcompany.myapp
- applinks:f87nv.app.goo.gl

**Comment by moori** [comment]
I´ve downloaded the firebase_unity_sdk_4.0.0.zip file from the site. I'm trusting this package to manage any iOS SDK.


I've setup the associated domains acordingly and assumed that if the deeplink was retrieved while the app was oppened and the app opens if I click on the link all Xcode configurations were all right.

**Comment by stewartmiles** [comment]
I just want to make sure I understand the test you're running:

- You have the app installed (this is important as the code path is different if the app isn't installed)
- You open a web browser / email app (e.g Safari)
- Click a dynamic link
- The app opens
- The link is *not* retrieved as expected

Is this what you're doing?

**Comment by moori** [comment]
That´s right.

And if I click the same link in the browser with the app running in background, I get the InviteReceived event inside Unity correctly (since sdk 4.0.0).

**Comment by stewartmiles** [comment]
Could you share the following to see whether we can reproduce your issue:
- Unity version
- OSX version
- Xcode version
- Target iOS SDK

Cheers,
Stewart

**Comment by stewartmiles** [comment]
Ok we've reproduced it with Unity 5.6.01f3, Xcode 8.3.2, iOS SDK 10.3.

What is odd is that the code path for opening a link when the app isn't installed e.g
- Click link
- Run through app install
- Open app
- Linked reported to app

Is working correctly and I'm pretty sure it's exactly the same flow as clicking on a link.  We'll take a look.

**Comment by stewartmiles** [comment]
We pushed a 4.0.1 bug fix release that should resolve this issue.
https://firebase.google.com/support/release-notes/unity#4.0.1

Cheers,
Stewart

**Comment by moori** [comment]
Thank you. I'll try right away!

**Comment by Roma6** [comment]
Hi, i am in the same team as @moori.
First of all, thank you @stewartmiles for the help and fast responses.

Unfortunately this release did not solve the issue.
And we tried to start to use the "DynamicLinks.DynamicLinkReceived" event handler (instead of "FirebaseInvites.InviteReceived"), but this caused a xcode build error (screenshot below).

Are we doing something wrong?

![a](https://user-images.githubusercontent.com/6913921/27306341-9d7b9480-551b-11e7-9e93-6dfb3a80e2ed.jpg)

**Comment by a-maurice** [comment]
Hi, I work on the same team as Stewart :)

So, that happens what the underlying static library is not being included.
In your Unity project, under "Assets/Plugins/iOS/Firebase", there should be
a "libDynamicLinks.a".

If it isn't there, import the DynamicLinks.unityBundle and make sure that
it is included during the import process.  If it is there, make sure that
in the Inspector, "iOS" is selected under Include Platforms.

Hopefully that solves your issue, but if it doesn't please let us know.

-Anthony

**Comment by Roma6** [comment]
Ok, what you said is right! "libDynamicLinks.a" was missing. 

I corrected that and build went successful, but it is still not receiving the DeepLink when clicking on a link  (at saffari) with the app closed.
Clicking on the same link with app opened (and minimized) I receive the DeepLink via "DynamicLinks.DynamicLinkReceived" AND "FirebaseInvites.InviteReceived" (and that's ok).

I started to think that I am not registering soon enough to the events, but I am doing this as soon as possible (on the first line of a Start of a MonoBehaviour in the first scene).

Just for the record, this is my Associated Domains:
![a](https://user-images.githubusercontent.com/6913921/27351239-0ae6ec10-55d3-11e7-93de-e4526fef181d.jpg)

**Comment by a-maurice** [comment]
Everything you described should be working, there isn't really a "soon enough" to be concerned about, it should be holding onto any deep links until a callback is registered on the event.

I've confirmed that case seems to be failing on our testapp as well.  We're looking into a fix, and will keep you updated.  Thanks for notifying us of this issue.

**Comment by jonsimantov** [comment]
Firebase Unity SDK version 4.0.2 has been released, which should resolve this issue: https://firebase.google.com/support/release-notes/unity#4.0.2

Jon

**Comment by moori** [comment]
Hello,

I´m getting the version 3.0.1 following this link:
https://firebase.google.com/docs/unity/setup

Is there another way to download 4.0.2?

**Comment by stewartmiles** [comment]
That's odd I'm seeing https://firebase.google.com/download/unity point to
https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_4.0.2.zip - as
expected .  Any chance you could share the region your downloading from or
the language you have the site set to?

Cheers,
Stewart

**Comment by moori** [comment]
You´re right. I´ve changed to English and got the 4.0.2.

The "Português Brasileiro" site is pointing to 3.0.1.

Thanks.

**Comment by moori** [comment]
We´ve just tested the 4.0.2 sdk and the problem persists.
The deeplink is not retrieved if it's opened when the app is installed and not running.
We´ll keep trying to figure out if we configured something wrong, but it doesn´t seems like.

Thanks

**Comment by Roma6** [comment]
We're still having the issue.
Are you working on a fix?
Shouldn't this issue be open?

Thanks.

**Comment by stewartmiles** [comment]
AFAIK we fixed this in 4.0.2.  Do you have a project - based upon our quickstart sample - that reproduces this issue?  There are many steps to follow to make sure a link is retrieved when the app starts up, if you don't follow the setup instructions the link will not be retrieved.

**Comment by Roma6** [comment]
We are trying to use this firebase  feature for some months. We tried so many things and this is not working.
Anyway, tomorrow we will prepare a repro of our project to send to you.

**Comment by Roma6** [comment]
The quickstart exemple is really working normally. But we are doing the same thing to our project and its not working. We will check if there is a incompatibility with another plugin.

**Comment by Roma6** [comment]
Our problema was a incompatibility with another plugin that implements UnityAppController. Removing it resolved the issue. Everything is working normally now. Thank you very much for all the help and fixes.
